### ISSUE TITLE
unable to run tests with gulp-jest

### ISSUE THREAD

**Issue by vyorkin** [vyorkin/flux-todo#1]
It works when i run jest with npm test script using config defined in [package.json](https://github.com/vyorkin/flux-todo/blob/master/package.json#L52)

but it fails when i'm trying to run it from a gulp task:
[task](https://github.com/vyorkin/flux-todo/blob/master/gulp/tasks/test.coffee), [config](https://github.com/vyorkin/flux-todo/blob/master/gulp/config/jest.coffee), [path](https://github.com/vyorkin/flux-todo/blob/master/gulp/config/paths.coffee)

```
coffeegulp test
[gulp] Using file /Users/vyorkin/programming/play/flux-todo/gulpfile.coffee
[gulp] Working directory changed to /Users/vyorkin/programming/play/flux-todo
[gulp] Running 'setConfig'...
[gulp] Finished 'setConfig' in 15 ms
[gulp] Running 'test'...
Found 2 matching tests...
 FAIL  dispatchers/app-dispatcher-spec.coffee
TypeError: Cannot call method 'getResourceByPath' of null
  at Loader._getNormalizedModuleID (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:360:40)
  at Loader.requireModule (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:813:23)
  at jasmineTestRunner (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/src/jasmineTestRunner/jasmineTestRunner.js:225:16)
  at /Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/src/TestRunner.js:370:12
  at _fulfilled (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/node_modules/q/q.js:798:54)
  at self.promiseDispatch.done (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/node_modules/q/q.js:827:30)
  at Promise.promise.promiseDispatch (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/node_modules/q/q.js:760:13)
  at /Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/node_modules/q/q.js:574:44
  at flush (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/node_modules/q/q.js:108:17)
  at /Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/src/lib/FakeTimers.js:259:7
  at process._tickCallback (node.js:419:13)

 FAIL  services/todo-service-spec.coffee
TypeError: Cannot call method 'getResourceByPath' of null
  at Loader._getNormalizedModuleID (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:360:40)
  at Loader.requireModule (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:813:23)
  at jasmineTestRunner (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/src/jasmineTestRunner/jasmineTestRunner.js:225:16)
  at /Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/src/TestRunner.js:370:12
  at _fulfilled (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/node_modules/q/q.js:798:54)
  at self.promiseDispatch.done (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/node_modules/q/q.js:827:30)
  at Promise.promise.promiseDispatch (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/node_modules/q/q.js:760:13)
  at /Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/node_modules/q/q.js:574:44
  at flush (/Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/node_modules/q/q.js:108:17)
  at /Users/vyorkin/programming/play/flux-todo/node_modules/jest-cli/src/lib/FakeTimers.js:259:7
  at process._tickCallback (node.js:419:13)

2 tests failed, 0 test passed (2 total)
Run time: 1.212s
[gulp] Finished 'test' in 1.26 s
```

**Comment by mattholland-dnb** [comment]
I'm having a similar issue. In my case, this only occurs occasionally and only on our Jenkins CI server - running in a local terminal is fine every time. @vyorkin did you get any further with this?

**Comment by vyorkin** [comment]
i've just gave up on this since its a "todo" project (% i don't know but may be you could try to call `jest.runCLI` directly instead of using gulp-jest

**Comment by naikus** [comment]
This also occurs if you use just.runCLI directly without using gulp-jest. I get this error on alternate invocations of gulp build.

**Comment by naikus** [comment]
Okay, I've found a workaround:
- Delete the node_modules/.haste_cache/cache-undefined file. (Or remove and re-install jest-cli node module)
- Name your jest configurations in your build file. e.g: 
```javascript
     gulp.task("test-datalayer", function(callback) {
       // jest.runCLI(options, packageroot, oncomplete)
       jest.runCLI({
         config: {
           name: "datalayer-tests", // <------ Give a unique name per configuration
           rootDir: config.src + "/datalayer/__tests__/",
           unmockedModulePathPatterns: [
             "node_modules/rx"
           ],
           moduleFileExtensions: [
             "js"
           ]
         }
       }, config.src + __dirname, onTestDone(callback));
     });
 ```
- Run your tests again. And It should succeed every time

**Comment by vyorkin** [comment]
cool, thanks, I'll try it

**Comment by vyorkin** [comment]
![selfie-0](http://i.imgur.com/eJ8FrZm.png)
